// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {logger} from '../models';
import {proxy} from '../models';
import {stats} from '../models';

export function GetConfig():Promise<config.Config>;

export function GetRecentLogs(arg1:number):Promise<Array<logger.Entry>>;

export function GetServerStatus():Promise<proxy.Status>;

export function GetStats():Promise<stats.Stats>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
