// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveConnections() {
  return window['go']['main']['App']['GetActiveConnections']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
